---
# tasks file for deploy
- name: install packages
  apt: name{{item}} state=installed
  with_items:
    - default-jdk
    - tomcat9

- name: Transfer war artifact
  synchronize:
    src: "{{ build_folder }}"
    dest: "{{ deploy_folder }}"
  delegate_to: build