---
# tasks file for deploy
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - tomcat9

- name: Transfer war artifact
  synchronize:
    src: "{{ build_folder }}"
    dest: "{{ deploy_folder }}"
  delegate_to: 34.123.212.87